const routes = require('next-routes')

module.exports = routes()
  .add('index', '/')
  .add('redirect', '/redirect')
  .add('post/new', '/post/new')
  .add('post', '/post/:postId')
  .add('users/profile/me', '/users/me')
  .add('users/leaderboard', '/users/leaderboard')
  .add('users/profile', '/users/:userId')
  .add('notfound', '/*')
